apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "main"
    - name: build-image
      type: string
      description: "Target image to build and push"

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      runAfter:
        - init
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces: 
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"
      runAfter:
        - clone
